import * as vscode from 'vscode';
import { Ad } from '../rendering/types';
import {
  ImpressionRecord,
  EarningsResponse,
  AdResponse,
  toAd,
} from './types';

/**
 * PRIVACY: ApiClient — Downbeat API communication layer
 *
 * This client sends ONLY the following data to the Downbeat server:
 *   1. Ad fetch requests: contain only the API key header (no user data)
 *   2. Impression records: { impression_id, duration_ms, clicked }
 *   3. Earnings queries: contain only the API key header (no user data)
 *
 * No terminal content, code, file paths, editor state, or any other
 * user data is ever included in any API request. The impression_id
 * is an opaque identifier generated by the server when the ad was fetched.
 */

const FLUSH_INTERVAL_MS = 30_000;

export class ApiClient {
  private apiUrl: string;
  private apiKey: string;

  /**
   * PRIVACY: This queue stores ONLY impression metadata:
   * { impressionId, durationMs, clicked }
   * No terminal content or user data is ever added to this queue.
   */
  private pendingImpressions: ImpressionRecord[] = [];
  private flushTimer: ReturnType<typeof setInterval> | undefined;

  constructor() {
    const config = vscode.workspace.getConfiguration('downbeat');
    this.apiUrl = config.get<string>('apiUrl', 'http://localhost:8000');
    this.apiKey = config.get<string>('apiKey', '');

    // Auto-flush queued impressions every 30 seconds
    this.flushTimer = setInterval(() => {
      this.flushImpressions().catch(() => {
        // Silently ignore flush errors — impressions stay queued for next attempt
      });
    }, FLUSH_INTERVAL_MS);
  }

  /**
   * Fetch an ad to display during AI thinking time.
   * PRIVACY: Request contains only the API key header. No user data.
   */
  async fetchAd(): Promise<Ad | null> {
    try {
      const response = await fetch(`${this.apiUrl}/api/v1/ad`, {
        method: 'GET',
        headers: this.headers(),
      });

      if (!response.ok) {
        return null;
      }

      const data = (await response.json()) as AdResponse;
      return toAd(data);
    } catch {
      return null;
    }
  }

  /**
   * Queue an impression for batch submission.
   * PRIVACY: Only stores { impressionId, durationMs, clicked }.
   * No terminal content, code, or user data is ever included.
   */
  recordImpression(
    impressionId: string,
    durationMs: number,
    clicked: boolean = false
  ): void {
    this.pendingImpressions.push({ impressionId, durationMs, clicked });
  }

  /**
   * Flush all queued impressions to the server.
   * PRIVACY: POST body contains only an array of
   * { impression_id, duration_ms, clicked } objects.
   * No terminal content or user data is ever transmitted.
   */
  async flushImpressions(): Promise<void> {
    if (this.pendingImpressions.length === 0) {
      return;
    }

    const batch = [...this.pendingImpressions];
    this.pendingImpressions = [];

    try {
      const response = await fetch(
        `${this.apiUrl}/api/v1/impressions/batch`,
        {
          method: 'POST',
          headers: {
            ...this.headers(),
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            impressions: batch.map((imp) => ({
              impression_id: imp.impressionId,
              duration_ms: imp.durationMs,
              clicked: imp.clicked,
            })),
          }),
        }
      );

      if (!response.ok) {
        // Re-queue on failure so impressions aren't lost
        this.pendingImpressions.unshift(...batch);
      }
    } catch {
      // Re-queue on network error
      this.pendingImpressions.unshift(...batch);
    }
  }

  /**
   * Fetch current earnings.
   * PRIVACY: Request contains only the API key header. No user data.
   */
  async fetchEarnings(): Promise<EarningsResponse> {
    try {
      const response = await fetch(`${this.apiUrl}/api/v1/earnings`, {
        method: 'GET',
        headers: this.headers(),
      });

      if (!response.ok) {
        return { today: 0, total: 0 };
      }

      return (await response.json()) as EarningsResponse;
    } catch {
      return { today: 0, total: 0 };
    }
  }

  private headers(): Record<string, string> {
    return {
      'X-Downbeat-Key': this.apiKey,
    };
  }

  dispose(): void {
    if (this.flushTimer !== undefined) {
      clearInterval(this.flushTimer);
    }
  }
}
